<a href="https://colab.research.google.com/github/g3ferreira/uea-fase-1/blob/main/classificacao_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
from sklearn.datasets import load_iris

#exploração de dados 

dt_iris = load_iris() #carregando o dataset 


print(dt_iris.keys()) #relacao dos campos que compoe o dataset
print(dt_iris['DESCR'][:200] + "\n...") # este valor é uma pequena descrição do dataset 
print(dt_iris['target_names']) #lista com os nomes das especies (classes) que pretendemos predizer
print(dt_iris['feature_names']) #lista com o nome dos atributos que uma iris possui
print(dt_iris['data']) #lista com os valores de cada iris contido no dataset
print(dt_iris['data'].shape) # valor contendo a quantidade de items no dataset e a quantidade de atributos em cada item
print(dt_iris['target']) #valor de classificação para cada item do data set, onde 0 é igual a setosa, 1 igual a versicolor e 2 virginica



dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...
['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5

In [66]:
#pre processamento, treinamento do modelo e avaliação do mesmo

from sklearn.model_selection import train_test_split
from sklearn import tree
import numpy as np
from random import uniform

from sklearn.metrics import classification_report

x_train, x_test, y_train, y_test = train_test_split(dt_iris['data'], dt_iris['target'], random_state=0) #dividindo o dataset para termos 75% dele como amostra para treinamento e 25% para teste 
tree_classifier = tree.DecisionTreeClassifier() #inicializando o classificador de árvore de decisão
tree_classifier.fit(x_train, y_train) #treinando o modelo

x_test  = np.array(x_test).astype(np.float32)
y_pred = tree_classifier.predict(x_test) #predição da iris utilizando o modelo treinado e as amostras de teste
print(classification_report(y_test,y_pred)) # exibindo o sumário com as principais métricas de avaliação do modelo treinado

print('Percentual de Acurácia: ',accuracy_score(y_pred,y_test))



              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38

Percentual de Acurácia:  0.9736842105263158


In [65]:
# laço para classificação de flores com valores dos atributos gerados automáticamente

for i in range(0,15):
  #gerando valores aleatórios para os atributos da iris para predição

  s_length = uniform(0, 7)
  s_width = uniform(0, 6)
  p_length = uniform(0, 3)
  p_width = uniform(0, 7)
  x_new_iris = np.array([[s_length, s_width, p_length, p_width]])  
  print(x_new_iris.shape)
  prediction_class = tree_classifier.predict(x_new_iris) #predição da iris utilizando o modelo treinado
  print(dt_iris['target_names'][prediction_class]) #exibindo o nome da classe de acordo com a predição do modelo



(1, 4)
['virginica']
(1, 4)
['setosa']
(1, 4)
['setosa']
(1, 4)
['versicolor']
(1, 4)
['virginica']
(1, 4)
['virginica']
(1, 4)
['versicolor']
(1, 4)
['virginica']
(1, 4)
['virginica']
(1, 4)
['virginica']
(1, 4)
['virginica']
(1, 4)
['versicolor']
(1, 4)
['virginica']
(1, 4)
['versicolor']
(1, 4)
['virginica']
